### ISSUE TITLE
gyp: binding.gyp not found when running 'node-gyp configure build'

### ISSUE THREAD

**Issue by kthblmfld** [rafaneri/hx711-addon#2]
Hello,

I am hoping to use the hx711 addon for a load sensor I am using on Arduino (code in javascript/johnny-five). However, when I run 'node-gyp configure build', I get error 
"gyp: binding.gyp not found (cwd: /.../hx711-addon-master) while trying to load binding.gyp"

Any idea how I can get this built and included?

Thanks

**Comment by rafaneri** [comment]
Hi @kthblmfld,

You tried run the node-gyp configure build on src directory? 
This addon uses the [intel mraa](https://github.com/intel-iot-devkit/mraa) to bind the data and clock pins.
You can use this sensor with the [intel upm](https://github.com/intel-iot-devkit/upm) too.

**Comment by kthblmfld** [comment]
Lol those are the pins I have been wondering about. I am building a robot using (johnny-five)[http://johnny-five.io/], and support for the HX711 isn't available (at least not yet). It sounds like I will need to shelve this feature for now as pin binding and node addons are beyond my capacity. Thanks for following up.
